from flask import Flask,render_template,request
import pickle
import numpy as np

  
app = Flask(__name__) #creating the Flask class object   
model=pickle.load(open('Adult_AdaBoost.pkl','rb'))
    
@app.route('/',methods=['GET']) #decorator drfines the   
def home(): 
 
    return render_template('index.html')

@app.route('/predict',methods=['GET','POST'])
def predict():
    
   if request.method=="POST":
        #Age 
        Age=int(request.form['age'])
        #Type_Employer
        Type_Employer=request.form['employertype']
        emptype_Private=0
        emptype_Selfemp_not_inc=0
        emptype_Local_gov=0
        emptype_State_gov=0
        emptype_Selfemp_inc=0
        emptype_Federal_gov=0
        emptype_Without_pay=0
        emptype_Never_worked=0
        if(Type_Employer=='Private'):
            emptype_Private=1
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=0
            emptype_State_gov=0
            emptype_Selfemp_inc=0
            emptype_Federal_gov=0
            emptype_Without_pay=0
            emptype_Never_worked=0
        elif(Type_Employer=='Selfemp-not_inc'):
            emptype_Private=0
            emptype_Selfemp_not_inc=1
            emptype_Local_gov=0
            emptype_State_gov=0
            emptype_Selfemp_inc=0
            emptype_Federal_gov=0
            emptype_Without_pay=0
            emptype_Never_worked=0
        elif(Type_Employer=='Local-gov'):
            emptype_Private=0
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=1
            emptype_State_gov=0
            emptype_Selfemp_inc=0
            emptype_Federal_gov=0
            emptype_Without_pay=0
            emptype_Never_worked=0
        elif(Type_Employer=='State-gov'):
            emptype_Private=0
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=0
            emptype_State_gov=1
            emptype_Selfemp_inc=0
            emptype_Federal_gov=0
            emptype_Without_pay=0
            emptype_Never_worked=0
        elif(Type_Employer=='Selfemp-inc'):
            emptype_Private=0
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=0
            emptype_State_gov=0
            emptype_Selfemp_inc=1
            emptype_Federal_gov=0
            emptype_Without_pay=0
            emptype_Never_worked=0
        elif(Type_Employer=='Federal-gov'):
            emptype_Private=0
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=0
            emptype_State_gov=0
            emptype_Selfemp_inc=0
            emptype_Federal_gov=1
            emptype_Without_pay=0
            emptype_Never_worked=0
        elif(Type_Employer=='Without_pay'):
            emptype_Private=0
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=0
            emptype_State_gov=0
            emptype_Selfemp_inc=0
            emptype_Federal_gov=0
            emptype_Without_pay=1
            emptype_Never_worked=0
        elif(Type_Employer=='Never_worked'):
            emptype_Private=0
            emptype_Selfemp_not_inc=0
            emptype_Local_gov=0
            emptype_State_gov=0
            emptype_Selfemp_inc=0
            emptype_Federal_gov=0
            emptype_Without_pay=0
            emptype_Never_worked=1
        #Education
        Education=request.form['education']
        edu=0
        if(Education=='Preschool'):
            edu=1
        elif(Education=='1st_to_4th'):
            edu=2
        elif(Education=='5th_to_6th'):
            edu=3
        elif(Education=='7th_to_8th'):
            edu=4
        elif(Education=='9th'):
            edu=5
        elif(Education=='10th'):
            edu=6
        elif(Education=='11th'):
            edu=7
        elif(Education=='12th'):
            edu=8
        elif(Education=='HS-grad'):
            edu=9
        elif(Education=='Some_college'):
            edu=10
        elif(Education=='Assoc_voc'):
            edu=11
        elif(Education=='Assoc_acdm'):
            edu=12
        elif(Education=='Bachelors'):
            edu=13
        elif(Education=='Masters'):
            edu=14
        elif(Education=='Prof_school'):
            edu=15
        elif(Education=='Doctorate'):
            edu=16
        #Marital Status ########################################################
        Marital=request.form['marital']
        mar_single=0
        mar_married=0
        if(Marital=='Single'):
            mar_single=1
            mar_married=0
        elif(Marital=='Married'):
            mar_single=0
            mar_married=1
        ##OCCUPATION ###########################################################
        Occupation=request.form['occupation']
        occup_Prof_specialty=0
        occup_Craft_repair=0
        occup_Exec_managerial=0
        occup_Adm_clerical=0
        occup_Sales=0
        occup_Other_service=0
        occup_Machine_op_inspct=0
        occup_Private=0
        occup_Transport_moving=0
        occup_Handlers_cleaners=0
        occup_Farming_fishing=0
        occup_Tech_support=0
        occup_Protective_serv=0
        occup_Armed_Forces=0
        occup_Priv_house_serv=0
        occup_Never_worked=0
        if(Occupation=='Prof_specialty'):
            occup_Prof_specialty=1
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Craft_repair'):
            occup_Prof_specialty=0
            occup_Craft_repair=1
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Exec_managerial'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=1
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Adm_clerical'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=1
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Sales'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=1
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Other_service'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=1
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Machine_op_inspct'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=1
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Private'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=1
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Transport_moving'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=1
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            Never_worked=0
        elif(Occupation=='Handlers_cleaners'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=1
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Farming_fishing'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=1
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Tech_support'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=1
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Protective_serv'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=1
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Armed_Forces'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=1
            occup_Priv_house_serv=0
            occup_Never_worked=0
        elif(Occupation=='Priv_house_serv'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=1
            occup_Never_worked=0
        elif(Occupation=='Never_worked'):
            occup_Prof_specialty=0
            occup_Craft_repair=0
            occup_Exec_managerial=0
            occup_Adm_clerical=0
            occup_Sales=0
            occup_Other_service=0
            occup_Machine_op_inspct=0
            occup_Private=0
            occup_Transport_moving=0
            occup_Handlers_cleaners=0
            occup_Farming_fishing=0
            occup_Tech_support=0
            occup_Protective_serv=0
            occup_Armed_Forces=0
            occup_Priv_house_serv=0
            occup_Never_worked=1
        Relationship=request.form['relationship']
        relatn_husband=0
        relatn_Not_in_family=0
        relatn_Own_child=0
        relatn_Unmarried=0
        relatn_Wife=0
        relatn_Other_relative=0
        if(Relationship=='Husband'):
            relatn_husband=1
            relatn_Not_in_family=0
            relatn_Own_child=0
            relatn_Unmarried=0
            relatn_Wife=0
            relatn_Other_relative=0
        elif(Relationship=='Not_in_family'):
            relatn_husband=0
            relatn_Not_in_family=1
            relatn_Own_child=0
            relatn_Unmarried=0
            relatn_Wife=0
            relatn_Other_relative=0
        elif(Relationship=='Own_child'):
            relatn_husband=0
            relatn_Not_in_family=0
            relatn_Own_child=1
            relatn_Unmarried=0
            relatn_Wife=0
            relatn_Other_relative=0
        elif(Relationship=='Unmarried'):
            relatn_husband=0
            relatn_Not_in_family=0
            relatn_Own_child=0
            relatn_Unmarried=1
            relatn_Wife=0
            relatn_Other_relative=0
        elif(Relationship=='Wife'):
            relatn_husband=0
            relatn_Not_in_family=0
            relatn_Own_child=0
            relatn_Unmarried=0
            relatn_Wife=1
            relatn_Other_relative=0
        elif(Relationship=='Other_relative'):
            relatn_husband=0
            relatn_Not_in_family=0
            relatn_Own_child=0
            relatn_Unmarried=0
            relatn_Wife=0
            relatn_Other_relative=1
        ### RACE ##############################################################
        Race=request.form['race']
        race_White=0
        race_Black=0
        race_Asian_Pac_Islander=0
        race_Amer_Indian_Eskimo=0
        race_Other=0
        if(Race=='White'):
            race_White=1
            race_Black=0
            race_Asian_Pac_Islander=0
            race_Amer_Indian_Eskimo=0
            race_Other=0
        elif(Race=='Black'):
            race_White=0
            race_Black=1
            race_Asian_Pac_Islander=0
            race_Amer_Indian_Eskimo=0
            race_Other=0
        elif(Race=='Asian_Pac_Islander'):
            race_White=0
            race_Black=0
            race_Asian_Pac_Islander=1
            race_Amer_Indian_Eskimo=0
            race_Other=0
        elif(Race=='Amer_Indian_Eskimo'):
            race_White=0
            race_Black=0
            race_Asian_Pac_Islander=0
            race_Amer_Indian_Eskimo=1
            race_Other=0
        elif(Race=='Other'):
            race_White=0
            race_Black=0
            race_Asian_Pac_Islander=0
            race_Amer_Indian_Eskimo=0
            race_Other=1
        Sex=request.form['sex']
        sex_Male=0
        sex_Female=0
        if(Sex=='Male'):
            sex_Male=1
            sex_Female=0
        elif(Sex=='Female'):
            sex_Male=0
            sex_Male=1
        ### Capital Gain ######################################################
        Capt_gain=int(request.form['capital_gain'])
        
        ### Capital Loss ######################################################
        capt_loss=int(request.form['capital_loss'])
        
        ### Hour Per Week
        hr_pr_week=int(request.form['hour_per_week'])
        hr_week=0
        if(hr_pr_week <40):
            hr_week=0
        elif((hr_pr_week >40) and (hr_pr_week < 60)):
            hr_week=1
        else:
            hr_week=2

        li=[Age,edu,Capt_gain,capt_loss,hr_week,emptype_Private,emptype_Selfemp_not_inc,emptype_Local_gov,emptype_State_gov,emptype_Selfemp_inc,
           emptype_Federal_gov,emptype_Without_pay,emptype_Never_worked,mar_single,mar_married,occup_Prof_specialty,
           occup_Craft_repair, occup_Exec_managerial,occup_Adm_clerical,occup_Sales,occup_Other_service,occup_Machine_op_inspct,
           occup_Private,occup_Transport_moving,occup_Handlers_cleaners,occup_Farming_fishing,occup_Tech_support,occup_Protective_serv,
           occup_Armed_Forces,occup_Priv_house_serv,occup_Never_worked,relatn_husband,relatn_Not_in_family,relatn_Own_child,
           relatn_Unmarried,relatn_Wife,relatn_Other_relative,race_White,race_Black,race_Asian_Pac_Islander,race_Amer_Indian_Eskimo,
           race_Other,sex_Male,sex_Female
           ]  
        
        X=[np.array(li)]

        pred=model.predict(X)[0]
        if(pred==1):
            return render_template('index.html',name='Congratulation!!.You will earn more than 50 K in future')
        else:
            return render_template('index.html',name='Do hard work to earn more than 50 k in future')
   else:
        return render_template('index.html',name='Not Run')
    
        

if __name__ =='__main__':  
    #app.run(debug = True)  
    app.run(debug=True, use_reloader=False)
    
    

    
